# -*- coding: utf-8 -*-
"""tesss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dB6uExw5mBAILrW8XT2JEqt2B5oW6I4b
"""

# ========== Imports ==========
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from joblib import load
import pickle
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

import plotly.express as px
import requests
import streamlit.components.v1 as components


# ========== Load Dataset ==========
url = 'https://raw.githubusercontent.com/Onlygall/Heart-attack/main/heart_attack_prediction_indonesia.csv'
data = pd.read_csv(url)
data['alcohol_consumption'] = data['alcohol_consumption'].fillna("None")


# ========== Sidebar ==========
pages = [
    "📰 Informasi",
    "📊 Tentang Dataset",
    "⚙️ Modeling",
    "🔮 Prediksi",
    "👥 About"
]

st.sidebar.title("Heart Attack")
page = st.sidebar.selectbox("Pilih Halaman", pages)


# ========== Halaman: Informasi ==========
if page == "📰 Informasi":

    # Load Lottie animation
    def load_lottieurl(url: str):
        r = requests.get(url)
        if r.status_code != 200:
            return None
        return r.json()

    lottie_heart = load_lottieurl("https://assets1.lottiefiles.com/packages/lf20_tutvdkg0.json")

    # Judul dan animasi
    st.title("💓 Serangan Jantung Di Indonesia")
    col1, col2 = st.columns([2, 1])

    with col1:
        st.markdown("### Statistik, Penyebab, dan Upaya Pencegahan")
        st.write("""
        Serangan jantung merupakan salah satu penyebab kematian utama di Indonesia...
        """)

    with col2:
        if lottie_heart:
            components.html(f"""
                <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
                <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_tutvdkg0.json"
                    background="transparent" speed="1" style="width: 100%; height: 150px;"
                    loop autoplay></lottie-player>
            """, height=180)

    # ========== Data ==========
    prevalensi_data = pd.DataFrame({
        "Tahun": [2013, 2018, 2023],
        "Prevalensi (%)": [0.5, 1.5, 0.85]
    })

    biaya_data = pd.DataFrame({
        "Tahun": [2014, 2016, 2018, 2023],
        "Biaya (Triliun Rp)": [4.4, 7.4, 9.3, 22.8]
    })

    usia_diagnosis_data = pd.DataFrame({
        "Tahun": [2013, 2023],
        "Usia Rata-rata (Tahun)": [48.5, 43.2]
    })

    kenaikan_usia_data = pd.DataFrame({
        "Kelompok Usia": ["< 45 Tahun", "≥ 46 Tahun"],
        "Kenaikan Kasus (%)": [66, 52]
    })

    provinsi_data = pd.DataFrame({
        "Provinsi": [
            "DI Yogyakarta", "Papua Tengah", "DKI Jakarta", "Jawa Barat", "Kalimantan Timur",
            "Bali", "Kalimantan Utara", "Kepulauan Riau", "Jawa Timur", "Sumatera Barat"
        ],
        "Prevalensi (%)": [1.67, 1.65, 1.56, 1.18, 1.08, 1.0, 0.95, 0.91, 0.88, 0.87]
    })

    # ========== Visualisasi ==========
    st.subheader("📈 Prevalensi Penyakit Jantung per Tahun")
    st.markdown("- **2013**: Prevalensi penyakit jantung sebesar **0,5%** ...")
    fig1 = px.line(prevalensi_data, x="Tahun", y="Prevalensi (%)", markers=True)
    st.plotly_chart(fig1, use_container_width=True)

    st.subheader("💰 Biaya Penanganan Penyakit Jantung oleh BPJS")
    st.markdown("- **2014**: BPJS Kesehatan mengeluarkan dana sebesar Rp4,4 triliun ...")
    fig2 = px.line(biaya_data, x="Tahun", y="Biaya (Triliun Rp)", markers=True,
                   color_discrete_sequence=["red"])
    st.plotly_chart(fig2, use_container_width=True)

    st.subheader("🧓 Usia Rata-rata Diagnosis Pertama")
    fig3 = px.bar(usia_diagnosis_data, x="Tahun", y="Usia Rata-rata (Tahun)",
                  color_discrete_sequence=["green"])
    st.plotly_chart(fig3, use_container_width=True)

    st.subheader("📊 Kenaikan Kasus Berdasarkan Kelompok Usia")
    fig4 = px.bar(kenaikan_usia_data, x="Kelompok Usia", y="Kenaikan Kasus (%)",
                  color_discrete_sequence=["purple"])
    st.plotly_chart(fig4, use_container_width=True)

    st.subheader("🏥 10 Provinsi dengan Prevalensi Tertinggi (2023)")
    fig5 = px.bar(provinsi_data, x="Prevalensi (%)", y="Provinsi", orientation='h',
                  color_discrete_sequence=["orange"])
    fig5.update_layout(yaxis=dict(autorange="reversed"))
    st.plotly_chart(fig5, use_container_width=True)

    # ========== Penutup ==========
    st.markdown("---")
    st.caption("Data bersumber dari Kemenkes, BPJS Kesehatan, dan Riskesdas.")

    st.markdown("### ⚠️ Faktor Risiko Utama")
    st.markdown("""
    - **Merokok**: Prevalensi merokok di kalangan pria dewasa ...
    """)

    st.markdown("### 🩺 Upaya Pencegahan dan Penanggulangan")
    st.markdown("*Sumber: [kemkes.go.id](https://kemkes.go.id)*")
    st.markdown("""
    - **Edukasi Masyarakat** ...
    """)