# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Pi7aZFfS_qo7rUCwS01T6O-Ek5z4-uT
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

# Sidebar Navigasi
st.sidebar.title("Heart attack")
page = st.sidebar.radio("Pilih Halaman", ["📄 Deskripsi Data", "🛠️ Modeling", "🔮 Prediksi"])

# ===============================
# Halaman: Deskripsi Data
# ===============================
if page == "📄 Deskripsi Data":
    st.title("🫀 Serangan Jantung di Indonesia")
    st.markdown("### Statistik, Penyebab, dan Upaya Pencegahan")

    # Penjelasan Umum
    st.markdown("""
    Serangan jantung merupakan salah satu penyebab kematian utama di Indonesia. Penyakit ini terjadi ketika aliran darah ke bagian jantung tersumbat, biasanya karena penumpukan lemak, kolesterol, dan zat lain.
    Menurut data Kementerian Kesehatan dan WHO, prevalensi penyakit jantung terus meningkat dari tahun ke tahun.

    Berikut adalah data dan informasi terkait tren serangan jantung di Indonesia.
    """)

    # ===============================
    # Data
    # ===============================
    prevalensi_data = pd.DataFrame({
        "Tahun": [2013, 2018, 2023],
        "Prevalensi (%)": [0.5, 1.5, 0.85]
    })

    biaya_data = pd.DataFrame({
        "Tahun": [2014, 2016, 2018, 2023],
        "Biaya (Triliun Rp)": [4.4, 7.4, 9.3, 22.8]
    })

    usia_diagnosis_data = pd.DataFrame({
        "Tahun": [2013, 2023],
        "Usia Rata-rata (Tahun)": [48.5, 43.2]
    })

    kenaikan_usia_data = pd.DataFrame({
        "Kelompok Usia": ["< 45 Tahun", "≥ 46 Tahun"],
        "Kenaikan Kasus (%)": [66, 52]
    })

    provinsi_data = pd.DataFrame({
        "Provinsi": [
            "DI Yogyakarta", "Papua Tengah", "DKI Jakarta", "Jawa Barat", "Kalimantan Timur",
            "Bali", "Kalimantan Utara", "Kepulauan Riau", "Jawa Timur", "Sumatera Barat"
        ],
        "Prevalensi (%)": [1.67, 1.65, 1.56, 1.18, 1.08, 1.0, 0.95, 0.91, 0.88, 0.87]
    })

    # ===============================
    # Visualisasi
    # ===============================
    st.subheader("📈 Prevalensi Penyakit Jantung per Tahun")
    fig1, ax1 = plt.subplots()
    ax1.plot(prevalensi_data["Tahun"], prevalensi_data["Prevalensi (%)"], marker='o', color='blue')
    ax1.set_ylabel("Prevalensi (%)")
    ax1.grid(True)
    st.pyplot(fig1)

    st.subheader("💰 Biaya Penanganan Penyakit Jantung oleh BPJS")
    fig2, ax2 = plt.subplots()
    ax2.plot(biaya_data["Tahun"], biaya_data["Biaya (Triliun Rp)"], marker='s', color='red')
    ax2.set_ylabel("Biaya (Triliun Rp)")
    ax2.grid(True)
    st.pyplot(fig2)

    st.subheader("👶 Usia Rata-rata Diagnosis Pertama")
    fig3, ax3 = plt.subplots()
    ax3.bar(usia_diagnosis_data["Tahun"], usia_diagnosis_data["Usia Rata-rata (Tahun)"], color='green')
    ax3.set_ylabel("Usia (Tahun)")
    ax3.grid(True)
    st.pyplot(fig3)

    st.subheader("📊 Kenaikan Kasus Berdasarkan Kelompok Usia")
    fig4, ax4 = plt.subplots()
    ax4.bar(kenaikan_usia_data["Kelompok Usia"], kenaikan_usia_data["Kenaikan Kasus (%)"], color='purple')
    ax4.set_ylabel("Kenaikan Kasus (%)")
    ax4.grid(True)
    st.pyplot(fig4)

    st.subheader("🏥 10 Provinsi dengan Prevalensi Tertinggi (2023)")
    fig5, ax5 = plt.subplots()
    ax5.barh(provinsi_data["Provinsi"], provinsi_data["Prevalensi (%)"], color='orange')
    ax5.set_xlabel("Prevalensi (%)")
    ax5.invert_yaxis()
    ax5.grid(True)
    st.pyplot(fig5)

    st.markdown("---")
    st.caption("Data bersumber dari Kemenkes, BPJS Kesehatan, dan laporan riset kesehatan dasar (Riskesdas).")

    # ===============================
    # Pencegahan
    # ===============================
    st.markdown("### 🩺 Pencegahan Serangan Jantung")
    st.markdown("""
    Beberapa cara pencegahan yang dapat dilakukan:
    - Menjaga pola makan sehat (rendah lemak dan kolesterol)
    - Olahraga teratur
    - Menghindari merokok dan alkohol
    - Rutin memeriksa tekanan darah dan kadar kolesterol
    - Mengelola stres dengan baik
    """)

    # ===============================
    # Sumber
    # ===============================
    st.markdown("### 📚 Sumber Data")
    st.markdown("""
    - Kementerian Kesehatan RI
    - WHO Indonesia
    - Data simulasi untuk keperluan demo
    """)

# ===============================
# Halaman: Modeling
# ===============================
elif page == "🛠️ Modeling":
    st.title("🛠️ Modeling Data")
    st.markdown("Konten modeling akan ditambahkan di sini.")

# ===============================
# Halaman: Prediksi
# ===============================
elif page == "🔮 Prediksi":
    st.title("🔮 Prediksi Heart Attack")
    st.markdown("Halaman prediksi akan dikembangkan lebih lanjut.")